/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2020-10-25T15:52:01. Do not modify directly. */

#include "buildinfo.h"

const struct buildinfo* ethminer_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_name = "ethminer",
        .project_version = "0.19.0-11+commit.d5f3a972.dirty",
        .project_name_with_version = "ethminer-0.19.0-11+commit.d5f3a972.dirty",
        .git_commit_hash = "d5f3a972220e06bf7b5d964d473d4c757e57e35d",
        .system_name = "linux",
        .system_processor = "x86_64",
        .compiler_id = "gnu",
        .compiler_version = "9.3.0",
        .build_type = "release",
    };
    return &buildinfo;
}
